name       : hdf5
version    : 1.8.17
release    : 2
source     :
    - http://www.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.8.17.tar.gz : d9cda297ee76ade9881c4208987939250d397bae6252d0ccb66fa7d24d67e263
license    : BSD-3-Clause
component  : programming
summary    : HDF5 is a data model, library, and file format for storing and managing data.
description: |
    HDF5 is a data model, library, and file format for storing and managing data.
setup      : |
    %configure --prefix=/usr --disable-static
build      : |
    %make
check      : |
    make check
install    : |
    %make_install
