name       : hdf5
version    : 1.8.19
release    : 4
source     :
    - https://support.hdfgroup.org/ftp/HDF5/prev-releases/hdf5-1.8/hdf5-1.8.19/src/hdf5-1.8.19.tar.gz : a4335849f19fae88c264fd0df046bc321a78c536b2548fc508627a790564dc38
license    : BSD-3-Clause
component  : programming
summary    : HDF5 is a data model, library, and file format for storing and managing data.
description: |
    HDF5 is a data model, library, and file format for storing and managing data.
patterns   :
    - devel :
        - /usr/share/hdf5_examples
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
