name       : hdf5
version    : 1.10.3
release    : 6
source     :
    - https://support.hdfgroup.org/ftp/HDF5/prev-releases/hdf5-1.10/hdf5-1.10.3/src/hdf5-1.10.3.tar.bz2 : c65cdcce4724a57fd3f8da9f0d109b497be30092acb9fac634d1291190d905a9
license    : BSD-3-Clause
component  : programming
summary    : HDF5 is a data model, library, and file format for storing and managing data
description: |
    HDF5 is a data model, library, and file format for storing and managing data. It supports an unlimited variety of datatypes, and is designed for flexible and efficient I/O and for high volume and complex data. HDF5 is portable and is extensible, allowing applications to evolve in their use of HDF5. The HDF5 Technology suite includes tools and applications for managing, manipulating, viewing, and analyzing data in the HDF5 format.
patterns   :
    - devel :
        - /usr/share/hdf5_examples
setup      : |
    %cmake_ninja -DHDF5_ENABLE_Z_LIB_SUPPORT=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
