name       : hdf5
version    : 1.10.4
release    : 7
source     :
    - https://support.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.10.4.tar.gz : 8f60dc4dd6ab5fcd23c750d1dc5bca3d0453bdce5c8cdaf0a4a61a9d1122adb2
license    : BSD-3-Clause
component  : programming
summary    : HDF5 is a data model, library, and file format for storing and managing data
description: |
    HDF5 is a data model, library, and file format for storing and managing data. It supports an unlimited variety of datatypes, and is designed for flexible and efficient I/O and for high volume and complex data. HDF5 is portable and is extensible, allowing applications to evolve in their use of HDF5. The HDF5 Technology suite includes tools and applications for managing, manipulating, viewing, and analyzing data in the HDF5 format.
setup      : |
    %cmake_ninja -DHDF5_ENABLE_Z_LIB_SUPPORT=ON \
                 -DHDF5_INSTALL_CMAKE_DIR=/usr/share/cmake \
                 -DHDF5_INSTALL_DATA_DIR=/usr/share/doc/hdf5 \
                 -DHDF5_INSTALL_LIB_DIR=%libdir%
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
