name       : hdf5
version    : 1.12.2
release    : 12
source     :
    - https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.12/hdf5-1.12.2/src/hdf5-1.12.2.tar.bz2 : 1a88bbe36213a2cea0c8397201a459643e7155c9dc91e062675b3fb07ee38afe
license    : BSD-3-Clause
component  : programming
summary    : HDF5 is a data model, library, and file format for storing and managing data
description: |
    HDF5 is a data model, library, and file format for storing and managing data. It supports an unlimited variety of datatypes, and is designed for flexible and efficient I/O and for high volume and complex data. HDF5 is portable and is extensible, allowing applications to evolve in their use of HDF5. The HDF5 Technology suite includes tools and applications for managing, manipulating, viewing, and analyzing data in the HDF5 format.
setup      : |
    # Run CMake to generate pkgconfig files
    %cmake_ninja -DHDF5_ENABLE_Z_LIB_SUPPORT=ON -DHDF5_INSTALL_LIB_DIR=%libdir%

    %configure \
        --disable-sharedlib-rpath \
        --disable-static \
        --enable-build-mode=production \
        --enable-hl \
        --enable-cxx \
        --with-pic \
        --with-zlib
build      : |
    %make
install    : |
    %make_install

    # Packagers always check these
    export PKGCONFIGDIR=$installdir/%libdir%/pkgconfig/
    install -dm00644 $PKGCONFIGDIR
    install -Dm00644 solusBuildDir/CMakeFiles/*.pc $PKGCONFIGDIR
    cp $PKGCONFIGDIR/hdf5.pc $PKGCONFIGDIR/hdf5-$version.pc
    cp $PKGCONFIGDIR/hdf5_hl.pc $PKGCONFIGDIR/hdf5_hl-$version.pc
check      : |
    export LD_LIBRARY_PATH="$installdir/%libdir%:$LD_LIBRARY_PATH"
    %make check
