name       : hdf5
version    : 1.10.2
release    : 5
source     :
    - https://support.hdfgroup.org/ftp/HDF5/prev-releases/hdf5-1.10/hdf5-1.10.2/src/hdf5-1.10.2.tar.bz2 : 1cad5b7bfdf128dfc53cd16fba48f6e7ae4e93c75c371d9ec8dfc4df0c1fcb71
license    : BSD-3-Clause
component  : programming
summary    : HDF5 is a data model, library, and file format for storing and managing data
description: |
    HDF5 is a data model, library, and file format for storing and managing data. It supports an unlimited variety of datatypes, and is designed for flexible and efficient I/O and for high volume and complex data. HDF5 is portable and is extensible, allowing applications to evolve in their use of HDF5. The HDF5 Technology suite includes tools and applications for managing, manipulating, viewing, and analyzing data in the HDF5 format.
patterns   :
    - devel :
        - /usr/share/hdf5_examples
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
