name       : hdf5
version    : 1.8.18
release    : 3
source     :
    - https://support.hdfgroup.org/ftp/HDF5/current18/src/hdf5-1.8.18.tar.gz : cdb195ad8d9e6782acf24b2488061289f615628c2ccda8457b0a0c3fb7a8a063
license    : BSD-3-Clause
component  : programming
summary    : HDF5 is a data model, library, and file format for storing and managing data.
description: |
    HDF5 is a data model, library, and file format for storing and managing data.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
patterns   :
    - devel :
        - /usr/share/hdf5_examples